version: '3.4'

services:
  database:
    container_name: database
    hostname: database
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=electron
      - POSTGRES_USER=admin
    volumes:
      - './content/database:/var/lib/postgresql/data'
  back:
    container_name: back
    links:
      - database
    build:
      context: ./back
    environment:
      - DATABASE_ADDRESS=database
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=123321
      - DATABASE_DB=electron
      - PATH_TO_FILES=/files/
    ports:
      - '8080:8080'
    volumes:
      - './content/files:/files'
  front:
    container_name: front
    links:
      - back
    build: 
      context: ./front
      # TODO: save picrutes on disk
    ports:
      - "80:80"
      - "443:443"
