version: '3.4'

services:
  database:
    container_name: database
    hostname: database
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=electron
      - POSTGRES_USER=admin
    volumes:
      - './content/database:/var/lib/postgresql/data'
  back:
    container_name: back
    links:
      - database
    build:
      context: ./back
    environment:
      - DATABASE_ADDRESS=database
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=123321
      - DATABASE_DB=electron
      - PATH_TO_FILES=/files/
    ports:
      - '8080:8080'
    volumes:
      - './content/files:/files'
  front:
    container_name: front
    links:
      - back
    build: 
      context: ./front
      # TODO: save picrutes on disk
    ports:
      - "80:80"
      - "443:443"
  elasticsearch:
    image: elasticsearch:7.1.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./content/elasticsearch:/usr/share2/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.1.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch