version: '3.4'

services:
  electron.database:
    container_name: electron.database
    hostname: database
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=electron
      - POSTGRES_USER=admin
    volumes:
      - '/var/electron-db:/var/lib/postgresql/data'
  electron.back:
    container_name: electron.back
    links:
      - electron.database
    build:
      context: ./back
    environment:
      - DATABASE_ADDRESS=database
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=123321
      - DATABASE_DB=electron
    ports:
      - '8080:8080'
    volumes:
      - ./target:/app
  electron.front:
    container_name: electron.front
    links:
      - electron.back
    build: 
      context: ./front
      # TODO: save picrutes on disk
    ports:
      - "80:80"